In [1]:
import pandas as pd

In [3]:
dataset=pd.read_csv("kidney_disease.csv")
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [17]:
def freqTable(columnName):
    freqTable=pd.DataFrame(columns=["Unique_Values","Frequency","Relative_F","Cumulative_RF"])
    freqTable["Unique_Values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative_F"]=freqTable["Frequency"]/len(freqTable["Unique_Values"])
    freqTable["Cumulative_RF"]=freqTable["Relative_F"].cumsum()
    
    return freqTable

In [18]:
freqTable("age")

    Unique_Values  Frequency  Relative_F  Cumulative_RF
0            60.0         19    0.250000       0.250000
1            65.0         17    0.223684       0.473684
2            48.0         12    0.157895       0.631579
3            55.0         12    0.157895       0.789474
4            50.0         12    0.157895       0.947368
..            ...        ...         ...            ...
71           83.0          1    0.013158       5.092105
72           27.0          1    0.013158       5.105263
73           14.0          1    0.013158       5.118421
74           81.0          1    0.013158       5.131579
75           79.0          1    0.013158       5.144737

[76 rows x 4 columns]

In [5]:
len(dataset)

400

In [9]:
len(dataset.columns)

26

In [10]:
len(dataset.shape)

2