In [1]:
# import library

import pandas as pd

In [2]:
# load dataset

dataset=pd.read_csv("kidney_disease.csv")
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [6]:
# Qualitative and Quantitative Data
# Categorical and Numerical data

qual=[]
quan=[]
for columnName in dataset.columns:
    if(dataset[columnName].dtypes=='O'):
        qual.append(columnName)
    else:
        quan.append(columnName)

In [26]:
def skewKurtosis(dataset,quan):
    descriptive=pd.DataFrame(index=["Skewness","Kurtosis"],columns=quan)
    for columnName in quan:
        descriptive[columnName]["Skewness"]=dataset[columnName].skew()
        descriptive[columnName]["Kurtosis"]=dataset[columnName].kurtosis()
        
    return descriptive

In [27]:
skewKurtosis(dataset,quan)

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Skewness,0.0,-0.668259,1.605429,-0.172444,0.998157,2.464262,2.010773,2.634374,7.509538,-6.996569,11.582956,-0.335095
Kurtosis,-1.2,0.05784,8.646095,-1.144357,-0.383377,5.055348,4.225594,9.345289,79.304345,85.53437,142.505912,-0.471398