In [1]:
# import library

import pandas as pd

In [2]:
# load dataset

dataset=pd.read_csv("kidney_disease.csv")
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [3]:
# Qualitative and Quantitative Data
# Categorical and Numerical data

qual=[]
quan=[]
for columnName in dataset.columns:
    if(dataset[columnName].dtypes=='O'):
        qual.append(columnName)
    else:
        quan.append(columnName)

In [4]:
def varianceSD(dataset,quan):
    descriptive=pd.DataFrame(index=["Variance","SD"],columns=quan)
    for columnName in quan:
        descriptive[columnName]["Variance"]=dataset[columnName].var()
        descriptive[columnName]["SD"]=dataset[columnName].std()
        
    return descriptive

In [5]:
varianceSD(dataset,quan)

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Variance,13366.666667,294.799082,187.241935,0.000033,1.82974,1.208221,6285.590212,2550.5536,32.960529,108.342119,10.201024,8.483161
SD,115.614301,17.169714,13.683637,0.005717,1.352679,1.099191,79.281714,50.503006,5.741126,10.408752,3.193904,2.912587